version: '2'
services:
    ulianko-mongodb:
        container_name: ulianko-mongodb
        image: mongo:3.2.3
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/ulianko/mongodb/:/data/db/
